// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu5vwKyScxRVW0hwnkS_UFLg1JA2d5opI',
    appId: '1:243788218913:android:a78535286cf8b03cf61960',
    messagingSenderId: '243788218913',
    projectId: 'expirymate-61a2a',
    storageBucket: 'expirymate-61a2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs1TDQ72ie2P2gUzAJh6wCren5RAJG38U',
    appId: '1:243788218913:ios:70b5dcc48246415ef61960',
    messagingSenderId: '243788218913',
    projectId: 'expirymate-61a2a',
    storageBucket: 'expirymate-61a2a.firebasestorage.app',
    androidClientId: '243788218913-8emvojo9dbii1qtqeqi3osddmns6vccc.apps.googleusercontent.com',
    iosClientId: '243788218913-e92b1c3823e6l9bb514ccc5jqs0uo37n.apps.googleusercontent.com',
    iosBundleId: 'com.haash.haashTrans',
  );

}